language: go

env:
  GO111MODULE="on"

script:      # 执行的脚步，但是go默认会执行（利用GOPATH下载依赖）go test ./...
#  - env GO111MODULE=on go build ./...
#  - env GO111MODULE=on go test
  - env GO111MODULE=on go test ./...